# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: echo.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\necho.proto\x12\x04\x65\x63ho\"\x1b\n\x0b\x45\x63hoRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"\x19\n\tEchoReply\x12\x0c\n\x04text\x18\x01 \x01(\t\"(\n\x13PrettifyJsonRequest\x12\x11\n\tjson_text\x18\x01 \x01(\t\"4\n\x14PrettifyJsonResponse\x12\x1c\n\x14prettified_json_text\x18\x01 \x01(\t2\x81\x01\n\x04\x45\x63ho\x12\x30\n\x08\x45\x63hoOnce\x12\x11.echo.EchoRequest\x1a\x0f.echo.EchoReply\"\x00\x12G\n\x0cPrettifyJson\x12\x19.echo.PrettifyJsonRequest\x1a\x1a.echo.PrettifyJsonResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'echo_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ECHOREQUEST']._serialized_start=20
  _globals['_ECHOREQUEST']._serialized_end=47
  _globals['_ECHOREPLY']._serialized_start=49
  _globals['_ECHOREPLY']._serialized_end=74
  _globals['_PRETTIFYJSONREQUEST']._serialized_start=76
  _globals['_PRETTIFYJSONREQUEST']._serialized_end=116
  _globals['_PRETTIFYJSONRESPONSE']._serialized_start=118
  _globals['_PRETTIFYJSONRESPONSE']._serialized_end=170
  _globals['_ECHO']._serialized_start=173
  _globals['_ECHO']._serialized_end=302
# @@protoc_insertion_point(module_scope)
