# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import echo_pb2 as echo__pb2


class EchoStub(object):
    """A tiny echo service.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.EchoOnce = channel.unary_unary(
                '/echo.Echo/EchoOnce',
                request_serializer=echo__pb2.EchoRequest.SerializeToString,
                response_deserializer=echo__pb2.EchoReply.FromString,
                )
        self.PrettifyJson = channel.unary_unary(
                '/echo.Echo/PrettifyJson',
                request_serializer=echo__pb2.PrettifyJsonRequest.SerializeToString,
                response_deserializer=echo__pb2.PrettifyJsonResponse.FromString,
                )


class EchoServicer(object):
    """A tiny echo service.
    """

    def EchoOnce(self, request, context):
        """Unary call: send text, get text back.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PrettifyJson(self, request, context):
        """Unary call: send JSON, get prettified JSON back.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EchoServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'EchoOnce': grpc.unary_unary_rpc_method_handler(
                    servicer.EchoOnce,
                    request_deserializer=echo__pb2.EchoRequest.FromString,
                    response_serializer=echo__pb2.EchoReply.SerializeToString,
            ),
            'PrettifyJson': grpc.unary_unary_rpc_method_handler(
                    servicer.PrettifyJson,
                    request_deserializer=echo__pb2.PrettifyJsonRequest.FromString,
                    response_serializer=echo__pb2.PrettifyJsonResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'echo.Echo', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Echo(object):
    """A tiny echo service.
    """

    @staticmethod
    def EchoOnce(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/echo.Echo/EchoOnce',
            echo__pb2.EchoRequest.SerializeToString,
            echo__pb2.EchoReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PrettifyJson(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/echo.Echo/PrettifyJson',
            echo__pb2.PrettifyJsonRequest.SerializeToString,
            echo__pb2.PrettifyJsonResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
